#!/bin/sh
INPFILE=$1
THREAD=$2
GVER=g16
RUNF=`echo "$GVER" | cut -c 1-3`
MSCR=/dev/shm/scratch_`whoami`_"$THREAD"
rm -rf ${MSCR}
mkdir ${MSCR}
chmod 777 ${MSCR}

export GAUSS_SCRDIR=${MSCR}
export GAUSS_EXEDIR="/s/ls4/groups/g0130/bin/"$GVER""
export GAUSS_ARCHDIR="/"$GVER"/arch"
export GMAIN=$GAUSS_EXEDIR
export LD_LIBRARY_PATH=$GAUSS_EXEDIR
export G09BASIS="/s/ls4/groups/g0130/bin/"$GVER"/basis"
export F_ERROPT1="271,271,2,1,2,2,2,2"
export TRAP_FPE="OVERFL=ABORT;DIVZERO=ABORT;INT_OVERFL=ABORT"
export MP_STACK_OVERFLOW="OFF"
export KMP_DUPLICATE_LIB_OK="TRUE"
export PATH=${GAUSS_EXEXDIR}:${PATH}
/s/ls4/groups/g0130/bin/"$GVER"/"$RUNF" $INPFILE
rm -rf ${MSCR}
